### ISSUE TITLE
Incorrect task encoding

### ISSUE THREAD

**Issue by teslitsky** [e-oj/Fawn#1]
Hello. Thank you for your solid work. 
I have found bug about encoding conditions like 
`task.update(User, { id: 123, balance: { $gte: 100 } })`
 I have error `Error: key $gte must not start with '$'`.
it's because `handle$Token` function do not encode second level conditions like `$gte`.

**Comment by e-oj** [comment]
I've pushed updates that address this issue. Review the updates to make sure it's all good. Thanks again for your help.
