### ISSUE TITLE
Mongoose

### ISSUE THREAD

**Issue by mathieug** [e-oj/Fawn#10]
This package is a great idea.
I think it should not depend on Mongoose and should work directly with `node-mongodb-native`. To use it with Mongoose should be an option/feature.

**Comment by e-oj** [comment]
Yeah. I've been thinking about that for a while now. It will definitely be implemented once I find the time.

**Comment by e-oj** [comment]
This has been implemented. Tasks will run using the driver by default with an option to use mongoose. Check the [docs](https://github.com/e-oj/Fawn#task_run) for details. Thanks for your input.

**Comment by fritx** [comment]
But seems the tests are still related with mongoose?

**Comment by e-oj** [comment]
Most of the tests run with the native driver actually.The mongoose tests are [here](https://github.com/e-oj/Fawn/blob/master/tests/task.tests.js#L293)

**Comment by fritx** [comment]
Nice, will try it now!
