### ISSUE TITLE
multi option does not appear to be working.

### ISSUE THREAD

**Issue by thedanielfactor** [e-oj/Fawn#15]
The following snippet of code works fine without the `{multi:true}` option but as soon as I add it something fails.  It does not hit the catch and it does not return anything to the client.

```
task.update("UserPresence", {sessionId: req.params.sessionId}, {sessionId: null})
                            .remove("GroupSession", {_id: req.params.sessionId})
                            .options({multi:true})
                            .run({useMongoose: true})
                            .then(function () {
                                res.send({message: "session " + req.params.sessionId + " has ended"});
                            }).catch(function (err) {
                                res.send(err);
                            });
```

node 6.11.1
mongoose 4.11.6
fawn 2.0.1

**Comment by e-oj** [comment]
The remove function doesn't have a multi option. It removes all matching docs by default

**Comment by e-oj** [comment]
The catch handles errors that occurred during the run. Attaching options to remove throws an error immediately and synchronously so the task never runs. But it should throw an error

**Comment by e-oj** [comment]
That said, I have considered adding the multi option to the write functions because both the driver and mongoose have implemented one/many functions (updateOne, removeMany, .. etc) for all write operations. If you feel that would be a useful feature, I can tag this as an enhancement and it will be implemented in the next release. @thedanielfactor

**Comment by thedanielfactor** [comment]
Ah, so I need to add the options to the update.  That is where I wanted it.  I am not sure why I put it on the remove.  I will try that.

**Comment by thedanielfactor** [comment]
I do like the one/many idea.  That would be useful.
