### ISSUE TITLE
save command is still written to db, even though subsequent save fails

### ISSUE THREAD

**Issue by rushabhnagda11** [e-oj/Fawn#18]
Both are mongoose schemas. 

`task.save(Product,product.product)
        .save(ProductFinals,_.assign(product.productFinal, {product_id : { $ojFuture : "0._id"}}))`

The data in the first command is fine.
Data for the second save command has a validation error (intentional).

     ` task.run({useMongoose : true})
      .then(() => {
        res.sendStatus(200)
      })
      .catch((err) => {
        console.log(JSON.stringify(err))
      })`

Expeceted behavior : Everything is rolled back
Observed Behavior : Goes to the error block of the run command, but the first save is committed to the db.

**Comment by e-oj** [comment]
can you show all the relevant code or give more information? I haven't been able to reproduce this issue.

**Comment by e-oj** [comment]
It could also be helpful if you showed what the db looked like before and after the run function was called.

**Comment by rushabhnagda11** [comment]
Figured the issue. modelName instead of collectionName in rollBackTask in roller. But mongoose pluralizes model names (i.e Product becomes products etc etc)

Also, I've not quite got the use of the iife in rollBackTask. Can't a let step = "" be used?

I can give a PR for this

**Comment by e-oj** [comment]
"let step" in place of iife will work but I don't want to mix different javascript versions. I might eventually refactor the whole library to use es6.

**Comment by e-oj** [comment]
Feel free to open a pr. They're always welcome 👍

**Comment by e-oj** [comment]
I've actually added this fix as part of the new release. Update your Fawn version and things should work fine. Feel free to reopen this issue if it persists. Thanks for your help 👍 👍
