### ISSUE TITLE
Can Fawn support soft delete?

### ISSUE THREAD

**Issue by zhengyhn** [e-oj/Fawn#26]
Hi,
    We don't have permission to remove records in production, can Fawn support soft delete? For example, use this package [mongoose-delete](https://github.com/dsanel/mongoose-delete).

**Comment by e-oj** [comment]
I'll say no, but that's just because implementations for soft delete are very subjective. You could just add a boolean "deleted" field and update it with the update method.

So instead of
```javascript
task.remove("things", {_id: someId})
```
you could do
```javascript
task.update("things", {_id: someId}, {deleted: true})
```
