### ISSUE TITLE
Not rolling back for update and remove (with _id)

### ISSUE THREAD

**Issue by skarif2** [e-oj/Fawn#34]
I have tried to use Fawn with mongoose. I have a sequence of save, update and update. If the second update fails the save is rolling back but not the first update.

```
const task = Fawn.Task();
task.save(Deposit, saveDeposit)
  .update(User, { _id: saveUser._id }, { $inc: { balance: amount } })
  .update(RechargeCard, { _id: saveRechargeCard.used }, { used: true })
  .run({ useMongoose: true })
  .then((results) => {
       res.json({
            status: 'success',
            results
       });
   })
   .catch((err) => {
       res.json({
            status: 'error',
            message: err
       });
   });
```

Is there any problem with Fawn or I'm making any mistake.

**Comment by skarif2** [comment]
`saveRecharge.used` is not an `ObjectId`. I did it intentionally so an error will happen.

**Comment by e-oj** [comment]
What version of Fawn are you using?

**Comment by e-oj** [comment]
Also, does it work without mongoose (useMongoose: false)?

**Comment by skarif2** [comment]
Using `useMongoose: false` works but the problem is it returns success on the second update where it should return error cause `saveRechargeCard.used` is _Boolean_ value not _ObjectId_ and moreover it doesn't update the _RechargeCard_ collection. If I use `useMongoose: true` and instead of using mongoose model use collection name like` 'deposits'`, `'users`' etc it does the same thing.

**Comment by e-oj** [comment]
Alright. What version of Fawn?

**Comment by skarif2** [comment]
`2.1.0`

**Comment by e-oj** [comment]
Looks like a bug. I'll look into it

**Comment by e-oj** [comment]
Having a string "id" field for queries would be a temporary fix

**Comment by skarif2** [comment]
I think it has something to do with mongoose validation.
```
const task = Fawn.Task();
task.update(User, { _id: saveUser._id }, { $inc: { balance: amount } })
  .update(RechargeCard, { _id: saveRechargeCard._id }, { used: true })
  .save(Deposit, saveDeposit)
  .run({ useMongoose: true })
  .then((results) => {
       res.json({
            status: 'success',
            results
       });
   })
   .catch((err) => {
       res.json({
            status: 'error',
            message: err
       });
   });
```
In the above code, I made a schema validation error in `saveDeposit` object and it returned the error currently but the first two updates didn't rollback, they made permanent change in db.

**Comment by e-oj** [comment]
Well, what happens is, Fawn uses the update condition to find documents about to be changed, then it stores a copy of the found docs for rollbacks. In the db, _id is stored as an ObjectId, not a string but Fawn converts the _id to a string (all objects passed to a task's functions are converted to json strings) and queries the db for an _id equal to that string. But an ObjectId is not equal to any string, so that query returns 0 matched documents and there's basically no state we can rollback to.

**Comment by e-oj** [comment]
I was able to reproduce this without validations on the schema. It explains why this affects the remove function as well

**Comment by skarif2** [comment]
Hey Emmanuel, is there any estimated date that we are having an update? I need to use **Fawn** in one of my **production** application. I'm working on that application day and night so can't help you with a pr. Really sorry for that.

**Comment by e-oj** [comment]
No problem. It's the last two weeks of the semester so I'm up to my neck with final exams and projects but I'll work towards pushing an update by the end of this week.

**Comment by e-oj** [comment]
This has been fixed. Thanks for catching this bug

**Comment by mnguyen25** [comment]
@e-oj I'm using 2.1.5 and still having the exact issue

**Comment by s4suryapal** [comment]
Hi,
I am facing same issue. How to solve it ?
If we use any other field rather than `_id`, its working.
Having issue with `_id` only.

**Comment by s4suryapal** [comment]
I fixed it with following : 

```
try {
  await new Fawn.Task()
  .update('collection', 
               { _id: mongoose.Types.ObjectId(req.params.id) } , 
               { name: 'test', desc: 'description })
  .run({useMongoose: true});
} 
catch(err) { console.log(err); }
```

**Comment by mnguyen25** [comment]
Hi @s4suryapal your code throws an error because of a parsing error when you try to parse an invalid ObjectId using `mongoose.Types.ObjectId` which is prior to the Fawn call.
