### ISSUE TITLE
Is Fawn support with Mongoose upgrade version in the future?

### ISSUE THREAD

**Issue by duchuy294** [e-oj/Fawn#35]
Hello e-oj, I need to know if the Mongoose library is upgrade, so your Fawn will continue to support us or it will occur's error?

**Comment by e-oj** [comment]
I'll be pushing an update in a few days to address some open bugs and bump the mongoose version. It should work fine as is though. You can also initialize with your version of mongoose. Are you getting any errors?

**Comment by duchuy294** [comment]
Alright. At now my program is no problem with your Library. I just want to make sure that work fine in the next version of Mongoose. Thank you so much!

**Comment by e-oj** [comment]
No problem 👍
