### ISSUE TITLE
Support for MongoDB 3.6

### ISSUE THREAD

**Issue by PrabhakarIOTree** [e-oj/Fawn#56]
Hi,

I am using Fawn with Mongodb 3.4 and it is working fine. I upgraded to MongoDB 3.6 and the transactions are not commiting.  Could you please let me now if mongodb 3.6 is supported by Fawn.

regds,
Prabhakar

**Comment by e-oj** [comment]
Can you add a snippet of the error you're getting? I'm holding back on updates because MongoDB is supposed to be adding transactions to the database soon

**Comment by MaBeuLux88** [comment]
MongoDB 4.0.0 was released on 27 June 2018 so now multi document ACID transactions are supported.
https://www.mongodb.com/transactions
