### ISSUE TITLE
Is the rollback safe?

### ISSUE THREAD

**Issue by marcospgp** [e-oj/Fawn#58]
Is it possible that between the time a document is retrieved and a transaction is attempted, the document has been updated by some other process?

This would mean if the transaction fails, the rollback will change the document back to an older version, losing the new data in the process.

Can this happen or is this prevented in some way?

**Comment by marcospgp** [comment]
There are a few interesting ways this could be prevented:

* Make documents have their `__v` field incremented on every operation. This means if a transaction fails, we can include the previous `__v` field in the rollback query, which will make it fail in case the document has been updated in the meantime.

**Comment by e-oj** [comment]
Answered [Here](https://github.com/e-oj/Fawn/issues/12)
