### ISSUE TITLE
Multiple Fawn Instances

### ISSUE THREAD

**Issue by daveyMedvedev** [e-oj/Fawn#60]
This may just be user error but in the case it isn't here goes:

I have multiple instances of mongo. Think replication. Found Fawn when researching how to handle transactions and rollbacks. I read in my connections from a JSON config file which contain an array of URL's. When calling my CRUD it works fine if I read in only 1 URL from the config. 
If I read in two, I get: 

OverwriteModelError: Cannot overwrite `OJLINTTASKCOLLECTION` model once compiled

I understand why this is happening, I am trying to instantiate fawn over a pre-existing instance. How can I go about using fawn to act as a TX Manager for multiple connections?

**Comment by e-oj** [comment]
You can provide a [collection name](https://github.com/e-oj/Fawn#fawn_init) unique to each connection. Pass it as the second argument to Fawn.Init()

**Comment by daveyMedvedev** [comment]
I saw that in the docs, what if my collections have the same name in both connections? Thank you for the prompt reply btw
