### ISSUE TITLE
Support for MongoDB 4.2 and mongoose version 5

### ISSUE THREAD

**Issue by RezaErfani67** [e-oj/Fawn#62]
hi
i have 2 update task but roll back not occurred...
```javascript
          var jask = Fawn.Task();
               jask.update("Task", {_id:taskResult._id},{isDone:true})
               jask.update("Task", {taskOrder:9, workflow:taskResult.workflow},{isActive:"error"})
               jask.run({useMongoose: true})
                   .then(function(results){
                       console.log("success")
                       return res.json(results)

                   })
                   .catch(function(err){
                       console.log("error occurred but rollback not occurred")

                       

                   });
```

**Comment by iamottosung** [comment]
Hey @RezaErfani67, is your program entering the catch block and printing the error message? What about the success case, are these documents getting updated? 

I'm in the middle of integrating Fawn into my app but it's neither executing the task nor causing any errors. It enters neither the `then` nor `catch`. I'm on mongo 4 and mongoose 5.2.15.

**Comment by RezaErfani67** [comment]
i test it on standalone mongo server and its not work...
after many search ... i found  that i should run replSet mongo server for transaction in mongo db
thanks

**Comment by e-oj** [comment]
#56
