### ISSUE TITLE
Support for MongoDB 3.4

### ISSUE THREAD

**Issue by HenryJsure** [e-oj/Fawn#67]
Hi:
  I am use Fawn with Mongodb 3.4 and it is not working for rollback , 
   const task = Fawn.Task();
   task.update('subject', {name: 'test'}, {phone: '13345550010'})
   task.save('subject', subject)
   try {
     let res = await task.run();
   } catch(err) {
     console.log('err---', err)
   }
  The update still succeeds when the save fails

  err log is: ' the update operation document must contain atomic operators.'
regds,
Henry

**Comment by HenryJsure** [comment]
I modified roller.js 163 lines  data = {$set: data} have to repair  
I wonder if it is reasonable for you to check

**Comment by e-oj** [comment]
It might be a problem with the MongoDB version. I'm working on adding native transactions to Fawn but you can use transactions directly with MongoDB > 4.0
