### ISSUE TITLE
Fawn only updates a single document even thgough multiple documents match the search criteria

### ISSUE THREAD

**Issue by lahiruchandima** [e-oj/Fawn#69]
I use following to update a collection with Fawn.

dbTransactionTask.update('receipts', {owner: owner, branch: branch}, {closed: true});

My expectation is that Fawn would update all documents matching criteria  {owner: owner, branch: branch}. But, fawn only updates a single document which matches the criteria. All other documents matching criteria remains untouched.

Is this the expected behavior? Is there any way to get all documents to update?

**Comment by e-oj** [comment]
You need to set the multi option to true

"""javascript
task.update(...).options({multi: true})
"""

[Documented here](https://github.com/e-oj/Fawn#task_options)

**Comment by e-oj** [comment]
I will be closing this issue. Feel free to reopen If you're still having trouble with the updates.
