### ISSUE TITLE
Updating subdocuments ignores complex keys

### ISSUE THREAD

**Issue by vaskas** [e-oj/Fawn#8]
Hi @e-oj, thanks for the much needed library.
It works fine for me in simpler cases however I can't make it update the subdocuments. 

The working MongoDB syntax I'm trying to replicate is:

```
db.getCollection('artists').update({'albums._id': ObjectId("5949472342f02d5a9b2f0d24")}, {$set: {'albums.$.name': "Beaver Scream"}})
```
The Fawn construct I'm trying to use is:
```
task.update("Artists", { 'albums._id': params.id }, { $set: { "albums.$.name": 'Beaver Scream'} })
```

However running it results in a BSON parser error:

```
key albums._id must not contain '.'
```

Not sure if I'm missing something or there is a bug. Would appreciate any pointers.

**Comment by e-oj** [comment]
Nice Catch. '$' and '.' are special characters in MongoDB. Currently, '$' is being escaped but '.' isn't. I'll look into it and push a fix soon.

**Comment by e-oj** [comment]
This has been fixed. Update your Fawn version and things should work fine

**Comment by vaskas** [comment]
You're a champion 🥇
