### ISSUE TITLE
Dynamic number of updates

### ISSUE THREAD

**Issue by avillarubia** [e-oj/Fawn#80]
Good day,

## Question
is it possible to loop multiple updates like this?

```
    Fawn.init(mongoose) <--initiliazed above
   
    .
    ..
    ...
    const task = new Fawn.Task()

    updates.map(({ _id, row }) => {
      task.update("accounts", { _id: _id }, { row: row })
    })

    task.run({ useMongoose: true })
```

I tried it but it does not work, tried also by async but doesn't work.
Hoping that you guys encounter this case and solved it.

Thank you.

**Comment by prasad1120** [comment]
Use `{ $set: { row: row} }` instead of `{ row: row }` and also check if _id is required as `mongoose.Types.ObjectId(_id)`.

Also, looks like this library is dead. Quite a few issues with it and no new releases since the early 2018. Best to avoid it.

**Comment by avillarubia** [comment]
@prasad1120 thank you for the response. Do you have any recommendations like this?
